Tranings/Ruby_&_Rails/library_management_system/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
     root 'home#index'

     get "/person/:id", to:"person#show_details",as:"person_detail"


     get "/book/:id", to:"book#show_details",as:"book_detail"

     get "/create_book", to:"book#create_book",as:"create_book"
     post "/create_book_form", to:"book#insert_book_form",as:"insert_book_form"

     get "/create_person", to:"person#create_person",as:"create_person"
     post "/create_person_form", to:"person#insert_person_form",as:"insert_person_form"
    
    # post "/create_book", to:"book#fill_detail",as:"fill_detail"


end

Tranings/Ruby_&_Rails/library_management_system/app/models/billing.rb
class Billing < ApplicationRecord
	  belongs_to :person
	  belongs_to :book,optional: true

end

Tranings/Ruby_&_Rails/library_management_system/app/models/book.rb
class Book < ApplicationRecord
	has_many :billings
end

Tranings/Ruby_&_Rails/library_management_system/app/models/department.rb
class Department < ApplicationRecord
	has_many :people
	#has_many :books , through: :billings 
	has_many :billings , through: :person
end

Tranings/Ruby_&_Rails/library_management_system/app/models/person.rb
class Person < ApplicationRecord
	has_many :billings
	has_many :books , through: :billing
	belongs_to :department 

	#validation :name , presence: true                                                                                                                                                                                                                                                              
end

Tranings/Ruby_&_Rails/library_management_system/app/controllers/book_controller.rb
class BookController < ApplicationController
		skip_before_action :verify_authenticity_token

	def show_details
	 
	  @book = Book.find(params[:id])
	end

	def create_book
          
     @create_book_form = Book.new
	end

	def insert_book_form	
         
      Book.create(book_title: params[:book_title], author: params[:author], price: params[:price])	


    end

	
  
    # def fill_detail
    # 	Book.create(book_params)
    	
    # end
	
end

Tranings/Ruby_&_Rails/library_management_system/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	
     	@billings = Billing.all.page(params[:page]).per_page(5)
    end
end

Tranings/Ruby_&_Rails/library_management_system/app/controllers/person_controller.rb
class PersonController < ApplicationController
	skip_before_action :verify_authenticity_token
	def show_details
	 
	@person = Person.find(params[:id])
	end

	 def create_person
    
	 	@insert_person_form = Person.new
		
	 end 



	def insert_person_form	
        
		Person.create(name: params[:name], mob: params[:mob], gender: params[:gender], address: params[:address], department_id: params[:department_id], person_type: params[:person_type])
	end
	



end

Tranings/Ruby_&_Rails/library_management_system/app/helpers/book_helper.rb
module BookHelper
end

Tranings/Ruby_&_Rails/library_management_system/app/views/home/index.html.erb
        <head>
      	  <style>
      	  	 .city
      	  	    {
      	  	    	background-color: gray;
      	  	    	color: black;
      	  	    	
      	  	    }
      	  	   table , th , td
      	  	   {
      	  	   	  border: 1px solid black;
      	  	   }
      	  </style>
        </head>
        <body style="background-color:powderblue;">
           <center><h1 style="background-color:DodgerBlue;">Library Management System</h1></center>
                     <%= image_tag "bs.png", :size => "100x100" %>          
           <center>
           <a href="https://www.google.co.in/" target="_blank"><q>Visit Google Search</q></a>
           </center>

           <div  style="background-color:pink;">

           <div style="display: inline-block;">
           	 
       `
           <div style="display: inline-block; vertical-align:top;padding-top: 20px;padding-left: 100px;">
           <center><h1><u>Detail About People.</u></h1></center>
           <h2>
           	<table class ="table">
           	  <tr>
           	    <td>Person Name</td>
           	    <td>Gender</td>
                <td>Contact</td>
           	    <td>address</td>
           	    <td>Person type</td>
                 <td>Person department</td>
                <td>Person book</td>

           	  </tr>

               <br>
              <% @billings.each do |billing| %>
              <tr>
                <td><%= link_to billing.person.name,person_detail_path(id: billing.person.id) %> </td>
                  <td><%= billing.person.gender %></td>
                  <td><%= billing.person.mob %></td>
                  <td><%= billing.person.address %></td>
                  <td><%= billing.person.person_type %></td>
                  <td><%= billing.person.department.name %></td>

                <td><%= link_to billing.book.book_title,book_detail_path(id: billing.book.id) %> </td>


              </tr>
              <% end %>
           	 
          </table></h2>

           </div>
           </div>
          <center><h1><mark><%= link_to "Create New Person",create_person_path %></mark></h1></center>
          <center><h1><mark><%= link_to "Create New Book",create_book_path %> </mark></h1></center>

           <%= will_paginate @billings, previous_label: h("previous"), next_label: h("next") %>
        </body>
  

Tranings/Ruby_&_Rails/library_management_system/app/views/person/create_person.html.erb
<body style="background-color: grey">
  
<h2>Fill The Person Details.</h2>
  <form action="/create_person_form" method="post">
     Name:<br>
    <input type="text" name="name" >
    <br>
    Mob:<br>
    <input type="text" name="mob" >
    <br>
    Gender:<br>
    <input type="text" name="gender" >
    <br>
    Address:<br>
    <input type="text" name="address" >
    <br>
    Person_type:<br>
    <input type="text" name="person_type" >
    <br>
    Department_no:<br>
    <input type="text" name="department_id" >
    <br><br>
    <br>
    <input type="submit" value="Submit">
  </form>
 
</body>

 

Tranings/Ruby_&_Rails/library_management_system/app/views/person/show_details.html.erb
<!DOCTYPE html>
  <html>
    <head>
	    <style>
        table, th, td 
          {
             border: 1px solid black;
             border-collapse: collapse;
          }
     </style>
  </head>
  <body style="background-color: grey;">
    <h2>Detail About Person</h2>
	  <table >
	    <tr>
          <td>Person Name</td>
          <td>Gender</td>
          <td>Contact</td>
          <td>address</td>
          <td>Person type</td>
          <td>Person department</td>
       </tr>
       <tr>
       	  <td><%= @person.name %></td>
          <td><%= @person.gender %></td>
          <td><%= @person.mob %></td>
          <td><%= @person.address %></td>
          <td><%= @person.person_type %></td>
          <td><%= @person.department.name %></td>
       </tr>
	   </table>

  </body>
</html> 