Tranings/Ruby_&_Rails/Basic_project/config/routes.rb
Rails.application.routes.draw do
  

   root 'person#show'

   get "/person/:id", to:"person#show",as:"person_detail"

   
   get "/home/:id", to:"home#show", as:"home_detail"

   get "/post/", to:"post#show", as:"post_detail"

   get "/post/:id", to:"post#new", as:"post_new_detail"

   get "/comment/", to:"comment#show", as:"comment_detail"

   get "/create", to:"post#create_form", as:"create_form"
   post "/create", to:"post#insert_form", as:"insert_form"

    get "/create_comment", to:"comment#create_form", as:"create_comment_form"
   post "/create_comment", to:"comment#insert_form", as:"insert_comment_form"




  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Tranings/Ruby_&_Rails/Basic_project/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post 
	belongs_to :person
end

Tranings/Ruby_&_Rails/Basic_project/app/models/home.rb
class Home < ApplicationRecord
	  has_many :people
	  has_many :pictures, :as => :imageable
end

Tranings/Ruby_&_Rails/Basic_project/app/models/person.rb
class Person < ApplicationRecord
	validates :name, :presence=> true, :length=>{:minimum=> 5}
	has_many :pictures, :as=> :imageable

	belongs_to :home
	has_many :posts
	has_many :comments
end

Tranings/Ruby_&_Rails/Basic_project/app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :imageable, :polymorphic => true
end

Tranings/Ruby_&_Rails/Basic_project/app/models/post.rb
class Post < ApplicationRecord
	belongs_to :person
	has_many :comments ,through: :person
end

Tranings/Ruby_&_Rails/Basic_project/app/controllers/comment_controller.rb
class CommentController < ApplicationController
    skip_before_action :verify_authenticity_token

	def show
		@comments = Comment.all
	end
	def new
		@comment = Comment.find(params[:id])
		
	end

	def create_form

		@new_form = Comment.new
	end

	def insert_form
		Comment.create(person_id: params[:person_id], post_id: params[:post_id], body: params[:body])
	end
end

Tranings/Ruby_&_Rails/Basic_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
		@home = Home.find(params[:id])
		
	end
end

Tranings/Ruby_&_Rails/Basic_project/app/controllers/new_controller.rb
class NewController < ApplicationController
  def f1
  end

  def f2
  end
end

Tranings/Ruby_&_Rails/Basic_project/app/controllers/person_controller.rb
class PersonController < ApplicationController
	def show
		@people = Person.all
		
	end
end

Tranings/Ruby_&_Rails/Basic_project/app/controllers/post_controller.rb
class PostController < ApplicationController
	skip_before_action :verify_authenticity_token


	def show
		@posts = Post.all
	end

	def new
		@post = Post.find(params[:id])
	end

	def create_form

		@new_form = Post.new
	end

	def insert_form
		Post.create(title: params[:title], person_id: params[:person_id])
	end
	
end

Tranings/Ruby_&_Rails/Basic_project/app/helpers/comment_helper.rb
module CommentHelper
end

Tranings/Ruby_&_Rails/Basic_project/app/helpers/home_helper.rb
module HomeHelper
end

Tranings/Ruby_&_Rails/Basic_project/app/helpers/new_helper.rb
module NewHelper
end

Tranings/Ruby_&_Rails/Basic_project/app/helpers/person_helper.rb
module PersonHelper
end

Tranings/Ruby_&_Rails/Basic_project/app/helpers/post_helper.rb
module PostHelper
end

Tranings/Ruby_&_Rails/Basic_project/app/views/comment/create_form.html.erb
  <h2>Fill The Comment Details.</h2>
  <form action="/create_comment" method="post">
     person id:<br>
    <input type="text" name="person_id" >
    <br>
    post id:<br>
    <input type="text" name="post_id" >
    <br>
    comment title<br>
    <input type="text" name="body" >
    <br>
    <br>
    <input type="submit" value="Submit">
  </form>
 

Tranings/Ruby_&_Rails/Basic_project/app/views/comment/show.html.erb
<h1>see all comments:</h1>
<table border="2">
   <tr>
   	  <td>
   	  	Post title
   	  </td>
   	  <td>
   	  	Posted by person
   	  </td>
   	  <td>
   	  	comment title
   	  </td>

   	  <td>
   	  	comment by person
   	  </td>
   </tr>
  
   <% @comments.each do |comment| %> 
	<tr>
        <td><%= comment.post.title %></td>
        <td><%= comment.post.person.name %></td>
        <td><%= comment.body %></td> 
        <td><%= comment.person.name %></td> 
       <% end %>
    </tr>

</table>
  <h2><%= link_to "write a comment", create_comment_form_path %></h2>

Tranings/Ruby_&_Rails/Basic_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Tranings/Ruby_&_Rails/Basic_project/app/views/new/f1.html.erb
<h1>New#f1</h1>
<p>Find me in app/views/new/f1.html.erb</p>

hello i am f1 page.

Tranings/Ruby_&_Rails/Basic_project/app/views/new/f2.html.erb
<h1>New#f2</h1>
<p>Find me in app/views/new/f2.html.erb</p>

hello i am f2 page.

Tranings/Ruby_&_Rails/Basic_project/app/views/person/show.html.erb
<h2>Home page.</h2>
<table border="2">
   <tr>
   	  <td>
   	  	Person name
   	  </td>
   	  <td>
   	  	person department
   	  </td>
   	  <td>
   	  	person home
   	  </td>
   </tr>
  
   	 <% @people.each do |person| %> 
	  <tr>
     <td><%= person.name %></td>
    <td><%= person.department %></td> 
    <td><%= link_to person.home.name, home_detail_path(id: person.home.id) %></td>
     <% end %>
    </tr>

</table>
<h2> <%= link_to "Show all posts:", post_detail_path %></h2>
<h2> <%= link_to "Show all comments:", comment_detail_path %></h2>

Tranings/Ruby_&_Rails/Basic_project/app/views/post/create_form.html.erb
  
<h2>Fill The Post Details.</h2>
  <form action="/create" method="post">
     post title:<br>
    <input type="text" name="title" >
    <br>
    person_id:<br>
    <input type="text" name="person_id" >
    <br>
    <br>
    <input type="submit" value="Submit">
  </form>
 

Tranings/Ruby_&_Rails/Basic_project/app/views/post/new.html.erb
hi, i am post view.

Tranings/Ruby_&_Rails/Basic_project/app/views/post/show.html.erb
<h1>see all post:</h1>
<table border="2">
   <tr>
   	  <td>
   	  	Post title
   	  </td>
   	  <td>
   	  	person name
   	  </td>
   </tr>
  
   	 <% @posts.each do |post| %> 
	  <tr>
     <td><%= post.title %></td>
    <td><%= post.person.name %></td> 
     <% end %>
    </tr>

</table>
  
  <h2><%= link_to "write a post", create_form_path %></h2>